trigger:
    branches:
        include:
            - main

pool:
    vmImage: ubuntu-latest

stages:
    - stage: Test
      displayName: Test Golang App
      jobs:
          - job: Test
            displayName: Test Golang App
            steps:
                - task: GoTool@0
                  inputs:
                      version: "1.17"
                  displayName: "Install and select Go version $1.17"
                - script: |
                      go test -v $(System.DefaultWorkingDirectory)
                  displayName: "Run unit tests"

    - stage: Build
      displayName: "Build Golang App"
      condition: succeeded()
      dependsOn: Test
      jobs:
          - template: azure-pipelines-build-template.yml
            parameters:
                imageName: "golang-azure"
                tags: "$(Build.SourceVersion)"

    - stage: DeployDEV
      displayName: "Deploy to DEV environment"
      condition: succeeded()
      dependsOn: Build
      variables:
          - group: "golang-dev-env-variable-group"
      jobs:
          - template: azure-pipelines-deployment-template.yml
            parameters:
                environment: "DEV"

    - stage: DeployPROD
      displayName: "Deploy to PROD environment"
      condition: succeeded()
      dependsOn:
          - Build
          - DeployDEV
      variables:
          - group: "golang-prod-env-variable-group"
      jobs:
          - template: azure-pipelines-deployment-template.yml
            parameters:
                environment: "PROD"
