trigger:
    branches:
        include:
            - develop

pool:
    vmImage: ubuntu-latest

stages:
    - stage: Build
      displayName: "Build Golang App"
      jobs:
          - template: azure-pipelines-build-template.yml
            parameters:
                imageName: "golang-azure"
                tags: "$(Build.SourceVersion)"

    - stage: DeployDEV
      displayName: "Deploy to DEV environment"
      condition: succeeded()
      dependsOn: Build
      variables:
          - group: "golang-dev-env-variable-group"
      jobs:
          - template: azure-pipelines-deployment-template.yml
            parameters:
                environment: $(Environment)
