jobs:
    - job:
      parameters:
          imageName: $
          env: $
          tags: $
      displayName: "Build Golang app"
      steps:
          - task: Docker@2
            displayName: Build image
            inputs:
                repository: $(parameters.imageName)
                command: build
                Dockerfile: $(System.DefaultWorkingDirectory)/Dockerfile
                tags: $(parameters.tags)
          - script: |
                docker save $(parameters.imageName):$(parameters.tags) > go.tar
          - task: PublishBuildArtifacts@1
            displayName: Publish package ready for $(parameters.env)
            inputs:
                PathtoPublish: "$(System.DefaultWorkingDirectory)/go.tar"
                artifactName: "image"
          - script: |
                docker images
