# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
    - main

pool:
    vmImage: ubuntu-latest

steps:
    - task: GoTool@0
      displayName: Install Go
      inputs:
          version: "1.17"
    - task: Go@0
      displayName: Build
      inputs:
          command: "build"
          workingDirectory: "$(System.DefaultWorkingDirectory)"
    - task: Go@0
      displayName: Test
      inputs:
          command: "test"
          arguments: "-v"
          workingDirectory: "$(modulePath)"
