trigger:
    branches:
        include:
            - develop

pool:
    vmImage: ubuntu-latest

stages:
    - stage: Build
      displayName: "Build Golang App"
      jobs:
          - template: ../azure-pipelines-build-template.yml
            parameters:
                imageName: "golang-azure"
                tags: "$(Build.SourceVersion)"

    - stage: RunDEV
      displayName: Run container
      variables:
          - group: "golang-dev-env-variable-group"
      jobs:
          - job:
            displayName: Running docker run
            steps:
                - script: |
                      ls
                      echo "hello docker in $(Environment)"
