trigger:
    branches:
        include:
            - develop

pool:
    vmImage: ubuntu-latest

stages:
    - stage: Build
      displayName: "Build Golang App"
      jobs:
          - template: ../azure-pipelines-build-template.yml
            parameters:
                imageName: "golang-azure"
                tags: "$(Build.SourceVersion)"

    - stage: RunDEV
      displayName: Run Container in DEV
      variables:
          - group: "golang-dev-env-variable-group"
      jobs:
          - job:
            displayName: Running docker run
            steps:
                - task: DownloadBuildArtifacts@0
                  displayName: "Download the build artifacts"
                  inputs:
                      buildType: "current"
                      downloadType: "single"
                      artifactName: "image"
                      downloadPath: "$(System.DefaultWorkingDirectory)"

                - script: |
                      ls ./image
                  displayName: Checking files
