trigger:
    - develop

pool:
    vmImage: ubuntu-latest

stages:
    - stage: Build
      displayName: "Build Golang App in dev environment"
      variables:
          - group: "golang-dev-env-variable-group"
      jobs:
          - template: ../azure-pupelines-build-template.yml
      parameters:
          imageName: golang-azure-$(Environment)-$(Build.SourceVersion)
          environment: $(Environment)

    - stage: RunDEV
      displayName: Run container
